insert into EMPLOYEE (ID, NAME,DESIGNATION,DATE_OF_BIRTH,SALARY)
values(10001,'madhu','dev', CURRENT_DATE,23456);

insert into EMPLOYEE (ID, NAME,DESIGNATION,DATE_OF_BIRTH,SALARY)
values(10002,'RAM','hr', CURRENT_DATE,22256);

insert into EMPLOYEE (ID, NAME,DESIGNATION,DATE_OF_BIRTH,SALARY)
values(10003,'vasavi','tester', CURRENT_DATE,23777);

insert into EMPLOYEE (ID, NAME,DESIGNATION,DATE_OF_BIRTH,SALARY)
values(10004,'surya','hr', CURRENT_DATE,53456);

insert into EMPLOYEE (ID, NAME,DESIGNATION,DATE_OF_BIRTH,SALARY)
values(10005,'jaanvi','tester', CURRENT_DATE,13456);

insert into EMPLOYEE (ID, NAME,DESIGNATION,DATE_OF_BIRTH,SALARY)
values(10006,'raksh','hr', CURRENT_DATE,44456);